### ISSUE TITLE
Didn't send to Telegram Bot

### ISSUE THREAD

**Issue by dxdigg** [CurryOnPatat/mail-php-tracking-with-gui#2]
I've changed the api key and the chat id.

api key was generated by botfater and the format is:xxxx:token
chatid was got from t.me/xxxx

so, what's the problem?
Plus, should we generate link each time for a different email address?

**Comment by CurryOnPatat** [comment]
I generate a different link for each email adress 
the chat id you only copy your chatid not the t.me/ if you dont know your chatid please watch this: https://www.youtube.com/watch?v=UPC5Ck1oU6k
